platform: linux
image_resource:
  type: docker-image
  source:
    repository: busybox
inputs:
  - name: src
params:
  ns_domain:
  ns_key:
  dest_dir:
run:
  path: sh
  args:
  - -ec
  - |
    echo "(mock) adding mpulse annotation"
    sleep 5
