platform: linux
image_resource:
  type: docker-image
  source:
    repository: ebiwd/alpine-ssh
inputs:
  - name: src
params:
  ns_domain:
  ns_key:
  dest_dir:
run:
  path: sh
  args:
  - -exc
  - |
    add-ssh-key sshacs "$ns_key"
    rsync -avz --delete -e "ssh -o HostKeyAlgorithms=+ssh-dss" src/public/ sshacs@$ns_domain:$dest_dir
