jobs:
  - name: deploy-dev
    public: true
    serial: true
    plan:
      - get: src-dev
        trigger: true

      - task: ns-dev
        params:
          ns_key: ((ns_key))
          ns_domain: ((ns_domain))
          dest_dir: "demo.a2s.ninja/dev.demo.a2s.ninja/"
        input_mapping:
          src: src-dev
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ebiwd/alpine-ssh
          inputs:
            - name: src
          run:
            path: sh
            args:
            - -exc
            - |
              add-ssh-key sshacs "$ns_key"
              rsync -avz --delete -e "ssh -o HostKeyAlgorithms=+ssh-dss" src/public/ sshacs@$ns_domain:$dest_dir

  - name: deploy-qa
    public: true
    serial: true
    plan:
      - get: src-qa
        trigger: true

      - task: ns-qa
        params:
          ns_key: ((ns_key))
          ns_domain: ((ns_domain))
          dest_dir: "demo.a2s.ninja/qa.demo.a2s.ninja/"
        input_mapping:
          src: src-qa
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ebiwd/alpine-ssh
          inputs:
            - name: src
          run:
            path: sh
            args:
            - -exc
            - |
              add-ssh-key sshacs "$ns_key"
              rsync -avz --delete -e "ssh -o HostKeyAlgorithms=+ssh-dss" src/public/ sshacs@$ns_domain:$dest_dir

  - name: deploy-prod
    public: true
    serial: true
    plan:
      - get: src-prod
        trigger: true

      - task: ns-prod
        params:
          ns_key: ((ns_key))
          ns_domain: ((ns_domain))
          dest_dir: "demo.a2s.ninja/prod.demo.a2s.ninja/"
        input_mapping:
          src: src-prod
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ebiwd/alpine-ssh
          inputs:
            - name: src
          run:
            path: sh
            args:
            - -exc
            - |
              add-ssh-key sshacs "$ns_key"
              rsync -avz --delete -e "ssh -o HostKeyAlgorithms=+ssh-dss" src/public/ sshacs@$ns_domain:$dest_dir

resources:
  - name: src-dev
    public: true
    type: git
    source:
      uri: git@github.com:ynohat/akamai-demo-site.git
      branch: dev
      private_key: ((github-deploy-key))

  - name: src-qa
    public: true
    type: git
    source:
      uri: git@github.com:ynohat/akamai-demo-site.git
      branch: qa
      private_key: ((github-deploy-key))

  - name: src-prod
    public: true
    type: git
    source:
      uri: git@github.com:ynohat/akamai-demo-site.git
      branch: qa
      private_key: ((github-deploy-key))
