jobs:
  - name: test-dev
    public: true
    plan:
      - get: src-dev
        trigger: true

      - task: run-tests
        input_mapping:
          src: src-dev
        file: src-dev/ci/tasks/test.yaml

  - name: deploy-dev
    public: true
    serial: true
    plan:
      - get: src-dev
        passed: [test-dev]

      - task: ns-dev
        params:
          ns_key: ((ns_key))
          ns_domain: ((ns_domain))
          dest_dir: "demo.a2s.ninja/dev.demo.a2s.ninja/"
        input_mapping:
          src: src-dev
        file: src-dev/ci/tasks/deploy.yaml

  - name: test-qa
    public: true
    plan:
      - get: src-qa
        trigger: true

      - task: run-tests
        input_mapping:
          src: src-qa
        file: src-qa/ci/tasks/test.yaml

  - name: deploy-qa
    public: true
    serial: true
    plan:
      - get: src-qa
        passed: [test-qa]

      - task: ns-qa
        params:
          ns_key: ((ns_key))
          ns_domain: ((ns_domain))
          dest_dir: "demo.a2s.ninja/qa.demo.a2s.ninja/"
        input_mapping:
          src: src-qa
        file: src-qa/ci/tasks/deploy.yaml

  - name: test-prod
    public: true
    plan:
      - get: src-prod
        trigger: true

      - task: run-tests
        input_mapping:
          src: src-prod
        file: src-prod/ci/tasks/test.yaml


  - name: deploy-prod
    public: true
    serial: true
    plan:
      - get: src-prod
        passed: [test-prod]

      - task: ns-prod
        params:
          ns_key: ((ns_key))
          ns_domain: ((ns_domain))
          dest_dir: "demo.a2s.ninja/prod.demo.a2s.ninja/"
        input_mapping:
          src: src-prod
        file: src-prod/ci/tasks/deploy.yaml

resources:
  - name: src-dev
    public: true
    type: git
    source:
      uri: git@github.com:ynohat/akamai-demo-site.git
      branch: dev
      private_key: ((github-deploy-key))

  - name: src-qa
    public: true
    type: git
    source:
      uri: git@github.com:ynohat/akamai-demo-site.git
      branch: qa
      private_key: ((github-deploy-key))

  - name: src-prod
    public: true
    type: git
    source:
      uri: git@github.com:ynohat/akamai-demo-site.git
      branch: qa
      private_key: ((github-deploy-key))
