jobs:
  - name: test-dev
    public: true
    plan:
      - get: src-dev
        trigger: true

      - task: run-tests
        input_mapping:
          src: src-dev
        file: src-dev/ci/tasks/test.yaml

  - name: deploy-dev
    public: true
    serial: true
    plan:
      - get: src-dev
        passed: [test-dev]
        trigger: true

      - task: ns-dev
        params:
          ns_key: ((ns_key))
          ns_domain: ((ns_domain))
          dest_dir: "demo.a2s.ninja/dev.demo.a2s.ninja/"
        input_mapping:
          src: src-dev
        file: src-dev/ci/tasks/deploy.yaml

  - name: purge-dev
    public: true
    serial: true
    plan:
      - get: src-dev
        passed: [deploy-dev]
        trigger: true

      - task: ns-dev
        params:
          cpcode: ((cpcode))
          edgerc: ((edgerc))
          edgerc_section: ccu
        input_mapping:
          src: src-dev
        file: src-dev/ci/tasks/purge.yaml

  - name: test-qa
    public: true
    plan:
      - get: src-qa
        trigger: true

      - task: run-tests
        input_mapping:
          src: src-qa
        file: src-qa/ci/tasks/test.yaml

  - name: deploy-qa
    public: true
    serial: true
    plan:
      - get: src-qa
        trigger: true
        passed: [test-qa]

      - task: ns-qa
        params:
          ns_key: ((ns_key))
          ns_domain: ((ns_domain))
          dest_dir: "demo.a2s.ninja/qa.demo.a2s.ninja/"
        input_mapping:
          src: src-qa
        file: src-qa/ci/tasks/deploy.yaml

  - name: purge-qa
    public: true
    serial: true
    plan:
      - get: src-qa
        trigger: true
        passed: [deploy-qa]

      - task: ns-qa
        params:
          cpcode: ((cpcode))
          edgerc: ((edgerc))
          edgerc_section: ccu
        input_mapping:
          src: src-qa
        file: src-qa/ci/tasks/purge.yaml

  - name: test-prod
    public: true
    plan:
      - get: src-prod
        trigger: true

      - task: run-tests
        input_mapping:
          src: src-prod
        file: src-prod/ci/tasks/test.yaml


  - name: deploy-prod
    public: true
    serial: true
    plan:
      - get: src-prod
        trigger: true
        passed: [test-prod]

      - task: ns-prod
        params:
          ns_key: ((ns_key))
          ns_domain: ((ns_domain))
          dest_dir: "demo.a2s.ninja/prod.demo.a2s.ninja/"
        input_mapping:
          src: src-prod
        file: src-prod/ci/tasks/deploy.yaml

  - name: purge-prod
    public: true
    serial: true
    plan:
      - get: src-prod
        trigger: true
        passed: [deploy-prod]

      - task: ns-prod
        params:
          cpcode: ((cpcode))
          edgerc: ((edgerc))
          edgerc_section: ccu
        input_mapping:
          src: src-prod
        file: src-prod/ci/tasks/purge.yaml

  - name: add-mpulse-annotation
    public: true
    serial: true
    plan:
      - get: src-prod
        trigger: true
        passed: [deploy-prod]

      - task: add-mpulse-annotation
        params:
          cpcode: ((cpcode))
          edgerc: ((edgerc))
          edgerc_section: ccu
        input_mapping:
          src: src-prod
        file: src-prod/ci/tasks/add-mpulse-annotation.yaml

  - name: perf-report
    public: true
    serial: true
    plan:
      - get: src-prod
        trigger: true
        passed: [deploy-prod]

      - task: generate
        file: src-prod/ci/tasks/test.yaml

      - put: slack
        params:
          text: "Performance report available"

  - name: load-test
    public: true
    serial: true
    plan:
      - get: src-prod
        trigger: true
        passed: [purge-prod]

      - task: run
        vars:
          url: http://prod.demo.a2s.ninja/index.html
          concurrency: 2
          duration: 1m
        file: src-prod/ci/tasks/load-test.yaml

      - put: slack
        params:
          text_file: output/log

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: src-dev
    public: true
    type: git
    source:
      uri: git@github.com:ynohat/akamai-demo-site.git
      branch: dev
      private_key: ((github-deploy-key))

  - name: src-qa
    public: true
    type: git
    source:
      uri: git@github.com:ynohat/akamai-demo-site.git
      branch: qa
      private_key: ((github-deploy-key))

  - name: src-prod
    public: true
    type: git
    source:
      uri: git@github.com:ynohat/akamai-demo-site.git
      branch: qa
      private_key: ((github-deploy-key))

  - name: slack
    type: slack-notification
    source:
      url: ((slack_webhook))